name: react-workflow
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: checkout code # cloning code in runner
        uses: actions/checkout@v4
        # with:

      - name: install nodejs in runner
        uses: actions/setup-node@v4
        with:
          node-version: 20.12.1
      
      - name: install dependencies
        run: npm install

      - name: run test
        run: npm run test